Add performPrep.py and tests
NeuroDataDesign/pyautomagic pull request #11
Opened 2019-10-31 23:52 UTC by rbechto2

This pull request combines work from Aamna, Liang, and Raphael to create performPrep.py and test_performPrep.py

2019-11-06 13:40 UTC, adam2392 commented
Okay it looks good. Try to link the codes into a cohesive pipeline and you can just run one integration test that tests the entire thing (removes redundancy). 

- link entire prep with ransac with robust referencing, etc. 
- include a jupyter notebook tutorial of what is going on here
- consider encapsulating functions that fall under same category under a class. See staticmethods, classmethods in python. 

^ for all above see graspy

2019-11-08 05:01 UTC, Nick3151 commented on pyautomagic/preprocessing/prep/noisychannels.py
> +        )
Dimensions seems not matching, robust_channel_deviation has original_dimension but i only goes through new_dimension

2019-12-01 21:40 UTC, adam2392 reviewed
Is "tests/test_data/S001R04.edf" necessary? Do you want to include this as a test file into the overall repo? If not, remove it from the PR.

Overall, I'm assuming this is to integrate the "PREP" pipeline functionality into pyautomagic right? If so, perhaps it would be helpful to get this merged in asap. @Nick3151 and @AamnaLawrence is this functional and is the code how you would like it? Can you insert your pyprep easily once it is done to wherever Raph has it set up?

I'll leave it up you two to approve this PR, and have it merged in. Then we can see if additional changes need to be made, and you two can submit issues related to that.

2019-12-01 21:41 UTC, adam2392 requested changes
Is "tests/test_data/S001R04.edf" necessary? Do you want to include this as a test file into the overall repo? If not, remove it from the PR. If so, ignore this.

2019-12-16 00:59 UTC, adam2392 commented
What is this PR vs the #13 one?

2019-12-16 01:26 UTC, closed without merging